export const segmentModel = [
    {
        type: 'select',
        name: 'region_id',
        placeholder: 'Territories',
        options: {
            1: 'Київська',
            2: 'Дніпропетровська',
            3: 'Вінницька',
            4: 'Запорізька',
            5: 'Волинська',
            6: 'Донецька',
            7: 'Житомирська',
            8: 'Закарпатська',
            9: 'Івано-Франківська',
            10: 'Кіровоградська',
            11: 'Луганська',
            12: 'Львівська',
            13: 'Миколаївська',
            14: 'Одеська',
            15: 'Полтавська',
            16: 'Рівненська',
            17: 'Сумська',
            18: 'Тернопільська',
            19: 'Харківська',
            20: 'Херсонська',
            21: 'Хмельницька',
            22: 'Черкаська',
            23: 'Чернівецька',
            24: 'Чернігівська',
            25: 'Автономна Республіка Крим',
        },
        initial_values: [],
    },
    {
        type: 'string',
        name: 'bot_type',
        placeholder: 'Platform',
        options: {
            telegram: 'Telegram',
            viber: 'Viber'
        },
        initial_values: '',
    },
    // {
    //     type: 'string',
    //     name: 'children_age',
    //     placeholder: 'Children age',
    //     options: ['3 years', '4 years', '5 years', '6 years'],
    //     initial_values: '',
    // },
    // {
    //     type: 'string',
    //     name: 'register_time',
    //     placeholder: 'Time of registration',
    //     options: [
    //         'Less then 6 month',
    //         '6 - 12 month',
    //         '12 - 18 month',
    //         'more than 18 month',
    //     ],
    //     initial_values: '',
    // },
    {
        type: 'string',
        name: 'recommendation_frequency',
        placeholder: 'Recommendation frequency',
        options: {
            daily: 'Once a day',
            weekly: 'Once a week'
        },
        initial_values: '',
    },
    // {
    //     type: 'string',
    //     name: 'child_number',
    //     placeholder: 'Number of children',
    //     options: [
    //         '1 child',
    //         '2 children',
    //         '3 children',
    //         '4 or more',
    //         ],
    //     initial_values: '',
    // },
    {
        type: 'string',
        name: 'customer_satisfaction',
        placeholder: 'Customer satisfaction',
        options: {
            'loyal': 'Loyal users',
            'dissatisfied': 'Dissatisfied users'
        },
        initial_values: '',
    },
    // {
    //     type: 'string',
    //     name: 'activity_period',
    //     placeholder: 'Activity period',
    //     options: ['7 days', '14 days', '21 days', 'Month', 'Quarter', 'Rarely'],
    //     initial_values: '',
    // },
]