export const segmentModelCustomerInfo = [
    {
        type: 'select',
        name: 'region_id',
        placeholder: 'Territories',
        options: {
            1: 'Київська',
            2: 'Дніпропетровська',
            3: 'Вінницька',
            4: 'Запорізька',
            5: 'Волинська',
            6: 'Донецька',
            7: 'Житомирська',
            8: 'Закарпатська',
            9: 'Івано-Франківська',
            10: 'Кіровоградська',
            11: 'Луганська',
            12: 'Львівська',
            13: 'Миколаївська',
            14: 'Одеська',
            15: 'Полтавська',
            16: 'Рівненська',
            17: 'Сумська',
            18: 'Тернопільська',
            19: 'Харківська',
            20: 'Херсонська',
            21: 'Хмельницька',
            22: 'Черкаська',
            23: 'Чернівецька',
            24: 'Чернігівська',
            25: 'Автономна Республіка Крим',
        },
        initial_values: [],
    },
    {
        type: 'string',
        name: 'bot_type',
        placeholder: 'Platform',
        options: {
            telegram: 'Telegram',
            viber: 'Viber'
        },
        initial_values: '',
    },
    {
        type: 'string',
        name: 'recommendation_frequency',
        placeholder: 'Recommendation frequency',
        options: {
            daily: 'Once a day',
            weekly: 'Once a week'
        },
        initial_values: '',
    },
    {
        type: 'string',
        name: 'customer_satisfaction',
        placeholder: 'Customer satisfaction',
        options: {
            'loyal': 'Loyal users',
            'dissatisfied': 'Dissatisfied users'
        },
        initial_values: '',
    },
    {
        type: 'slider',
        name: 'register_time',
        placeholder: 'Time of registration',
        options: [
            {value: 0, label: '0'},
            {value: 6, label: '6'},
            {value: 12, label: '12'},
            {value: 18, label: '18'},
            {value: 24, label: '24'},
            {value: 30, label: '30'},
        ],
        start: 0,
        end: 30,
        initial_values: [6, 12],
    },
]

export const segmentModelFamilyInfo = [
    {
        type: 'string',
        name: 'activity_period',
        placeholder: 'Activity period',
        options: ['7 days', '14 days', '21 days', 'Month', 'Quarter', 'Rarely'],
        initial_values: '',
    },
    {
        type: 'slider',
        name: 'child_number',
        placeholder: 'Number of children',
        options: [
            {value: 0, label: '0'},
            {value: 1, label: '1'},
            {value: 2, label: '2'},
            {value: 3, label: '3'},
            {value: 4, label: '4'},
            {value: 5, label: '5'},
        ],
        start: 0,
        end: 5,
        initial_values: [1, 3],
    },
    {
        type: 'slider',
        name: 'children_age',
        placeholder: 'Children age',
        options: [{value: 0, label: '0'},
            {value: 1, label: '1'},
            {value: 2, label: '2'},
            {value: 3, label: '3'},
            {value: 4, label: '4'},
            {value: 5, label: '5'},
        ],
        start: 0,
        end: 5,
        initial_values: [0, 2],
    },
]